### ISSUE TITLE
Update default order statuses

### ISSUE THREAD

**Issue by bitstein** [btcpayserver/woocommerce-plugin#8]
Currently, the default order status for "Complete" is "Processing". This should be updated to "Completed."
![screen shot 2018-08-12 at 10 04 37 am](https://user-images.githubusercontent.com/4544062/44003412-e51c39d4-9e17-11e8-91cb-6dd5f4fecd3e.png)

**Comment by bitstein** [comment]
On second thought, these defaults might be correct if "completed" is expected to be set by a different mechanism, for instance, a shipping plugin. I'm new to Woocommerce, so I'm still trying to make sense of some of the settings.

**Comment by NicolasDorier** [comment]
invoking the expert @astupidmoose

**Comment by astupidmoose** [comment]
Are these the defaults? 

New order being put on hold seems off to be, but not a big deal. 

"Paid" is when the payment is detected but no confirmations have been detected, "Confirmed" is once you hit the desired confirmations and "Complete" is basically built for legacy bitpay users and is when the order hits 6 confirmations. 

If you have 0 confirmation orders as shown above, you would likely want to leave confirmed and complete blank because its possible you process your order and BTCPay hits another threshold of confirmations and resets it back to the status set for that threshold. 

For example, We process orders after 2 confirmations, so we have "Completed" blank as we don't want or care about the 6 confirmation mark that Bitpay wants.

**Comment by NicolasDorier** [comment]
do you think the defaults are bad?

**Comment by bitstein** [comment]
@astupidmoose Thanks for that information.

> We process orders after 2 confirmations

Does this mean you also keep "Paid" blank?

**Comment by astupidmoose** [comment]
@NicolasDorier no, I think it makes sense for most, but not for us. Maybe ask @bitcoinshirt how he's working his system too. 

> Does this mean you also keep "Paid" blank?

No, we actually have some custom woocommerce statuses that we have enabled, but if we didn't we probably would. I'm not sure how else you would differentiate the statuses with the default ones from woocommerce. 

![image](https://user-images.githubusercontent.com/3916318/44044669-2b5e5fbc-9edb-11e8-8cbf-8717b828b1bc.png)


If you are doing 0 confirmation orders, I would mark Paid as processing, and leave confirmed and completed as blank.

**Comment by bitstein** [comment]
We are using 2 confirmations. I noticed the note in Woocommerce says "BTCPay invoice confirmed. Awaiting payment completed status."
https://github.com/btcpayserver/woocommerce-plugin/blob/748fd3fb0729d71aa3f6a264715c917b1f63833f/src/class-wc-gateway-bitpay.php#L1026

Is this just legacy cruft from BitPay and can otherwise be ignored?

**Comment by astupidmoose** [comment]
Yea, "Payment Completed status" is from bitpay and was always sent at 6 confirmations. Thats the "Completed" status. 

We've left it blank and have been successfully ignoring it for months now. Once you get 6 confirmations BTCPay will still send a note saying that status hit, but doesn't affect your status if left blank in the settings.

**Comment by bitcoinshirt** [comment]
I think this issue can be closed now. In 3.0 we've added new default statuses which are more generic. At the end of the day, it comes down to merchant and the specific needs, so it's a trial and error, which has [been documented here recently.](https://docs.btcpayserver.org/integrations/woocommerce#6-customizing-btcpay-woocommerce-plugin)

![screen shot 2018-12-08 at 01 27 40](https://user-images.githubusercontent.com/36959754/49679033-be4cca80-fa88-11e8-9f1a-9729145de0e8.png)
